apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- katib-mysql-deployment.yaml
- katib-mysql-pvc.yaml
- katib-mysql-secret.yaml
- katib-mysql-service.yaml
patchesStrategicMerge:
- katib-db-manager-deployment.yaml
