# The configuration for the ML pipelines APIServer
# Based on https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/config/config.json
apiVersion: v1
data:
  # apiserver assumes the config is named config.json
  # temporarily switched to kf-user, because pipeline-runner isn't bound to workload identity by default
  config.json: |
    {
      "DBConfig": {
        "DriverName": "mysql",
        "DataSourceName": "",
        "DBName": "mlpipeline"
      },
      "ObjectStoreConfig":{
        "AccessKey": "minio",
        "SecretAccessKey": "minio123",
        "BucketName": "mlpipeline",
        "PipelinePath": "pipelines"
      },
      "InitConnectionTimeout": "6m",
      "DefaultPipelineRunnerServiceAccount": "default-editor",
      "VisualizationService":{
        "Name": "ml-pipeline-visualizationserver",
        "Port": 8888
      }
      "MULTIUSER": true
    }
kind: ConfigMap
metadata:
  name: ml-pipeline-config
