{{- if .Values.profileController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app: kubeflow-pipelines-profile-controller
  annotations:
    {{- include "kubeflow-pipelines.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.profileController.replicas }}
  selector:
    matchLabels:
      app: kubeflow-pipelines-profile-controller
      app.kubernetes.io/component: ml-pipeline
      app.kubernetes.io/name: kubeflow-pipelines
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      labels:
        {{- include "kubeflow-pipelines.labels" . | nindent 8 }}
        app: kubeflow-pipelines-profile-controller
        sidecar.istio.io/inject: "false"
      annotations:
        {{- include "kubeflow-pipelines.annotations" . | nindent 8 }}
    spec:
      {{- include "kubeflow-pipelines.imagePullSecrets" . | nindent 6 }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: profile-controller
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        image: {{ .Values.profileController.image.repository }}:{{ .Values.profileController.image.tag }}
        command: ["python", "/hooks/sync.py"]
        envFrom:
        - configMapRef:
            name: kubeflow-pipelines-profile-controller-env
        env:
        - name: KFP_VERSION
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: appVersion
        - name: AWS_ENDPOINT_URL
          value: {{ .Values.seaweedfs.awsEndpointUrl }}
        - name: S3_ENDPOINT_URL
          value: {{ .Values.seaweedfs.s3EndpointUrl }}
        - name: AWS_REGION
          value: {{ .Values.seaweedfs.awsRegion }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: mlpipeline-minio-artifact
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: mlpipeline-minio-artifact
        - name: KFP_DEFAULT_PIPELINE_ROOT
          valueFrom:
            configMapKeyRef:
              key: defaultPipelineRoot
              name: pipeline-install-config
              optional: true
        - name: ARTIFACTS_PROXY_ENABLED
          valueFrom:
            configMapKeyRef:
              key: ARTIFACTS_PROXY_ENABLED
              name: pipeline-install-config
              optional: true
        - name: ARTIFACT_RETENTION_DAYS
          valueFrom:
            configMapKeyRef:
              key: ARTIFACT_RETENTION_DAYS
              name: pipeline-install-config
        {{- range .Values.profileController.additionalEnv }}
        - name: {{ .name }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- else if .valueFrom }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- else }}
          value: ""
          {{- end }}
        {{- end }}
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        ports:
        - containerPort: 8080
      volumes:
      - name: hooks
        configMap:
          name: kubeflow-pipelines-profile-controller-code
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
