apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
commonLabels:
  app: ml-pipeline-scheduledworkflow
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
images:
- name: gcr.io/ml-pipeline/scheduledworkflow
  newTag: 0.3.0
  newName: gcr.io/ml-pipeline/scheduledworkflow
vars:
- name: namespace
  objref:
    kind: ServiceAccount
    name: ml-pipeline-scheduledworkflow
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
configurations:
- params.yaml
