{{- if .Values.thirdParty.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      application-crd-id: kubeflow-pipelines
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        application-crd-id: kubeflow-pipelines
    spec:
      serviceAccountName: mysql
      containers:
      - args:
        # https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_ignore-db-dir
        # Ext4, Btrfs etc. volumes root directories have a lost+found directory that should not be treated as a database.
        # ignore-db-dir option has been deprecated in mysql v5.7.16.
        #
        # If upgrading MySQL to v8.0 fails, try removing /var/lib/mysql/lost+found folder in
        # mysql-pv-claim (mysql-persistent-storage):
        #
        # kubectl exec -it <mysql-pod-name> -n kubeflow -- bash
        # rm -rf /var/lib/mysql/lost+found
        #
        # More details on upgrading MySQL can be found here:
        # https://dev.mysql.com/doc/refman/8.0/en/upgrade-prerequisites.html
        # https://dev.mysql.com/doc/refman/8.0/en/upgrade-docker-mysql.html
        - --datadir
        - /var/lib/mysql
        # MLMD workloads (metadata-grpc-deployment and metadata-writer) depend on mysql_native_password authentication plugin.
        # mysql_native_password plugin implements native authentication; that is, authentication based on the password
        # hashing method in use from before the introduction of pluggable authentication in MySQL 8.0.
        #
        # The mysql_native_password authentication plugin is deprecated as of MySQL 8.0.34, disabled by default
        # in MySQL 8.4, and removed as of MySQL 9.0.0:
        # https://dev.mysql.com/doc/refman/8.4/en/native-pluggable-authentication.html
        - --authentication-policy=mysql_native_password
        - --mysql-native-password=ON
        # Disable binlog as the logs grow fast and eat up all disk spaces eventually. And KFP doesn't currently utilize binlog.
        # https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#option_mysqld_log-bin
        - --disable-log-bin
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        image: {{ .Values.thirdParty.mysql.image }}:{{ .Values.thirdParty.mysql.imageTag }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        securityContext:
          {{- toYaml .Values.thirdParty.mysql.securityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
        resources:
          {{- toYaml .Values.thirdParty.mysql.resources | nindent 10 }}
      securityContext:
        {{- toYaml .Values.thirdParty.mysql.podSecurityContext | nindent 8 }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
{{- end }}

