{{- if .Values.thirdParty.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
spec:
  ports:
  - # We cannot have name: mysql here, because some requests through istio fail with it.
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    application-crd-id: kubeflow-pipelines
{{- end }}

