bases:
- ambassador/base
- centraldashboard/overlay
- argo/base
- jupyter-web-app/base
- notebook-controller/base
- katib/v1alpha1/base
- profiles/base
- metacontroller/base
commonLabels:
  app: kubeflow

namespace: kubeflow
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
