apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- virtual-service.yaml
configMapGenerator:
- name: tektoncd-istio-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: clusterDomain
  objref:
    kind: ConfigMap
    name: tektoncd-istio-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.clusterDomain
configurations:
- params.yaml
