{{- if and .Values.seaweedfs.enabled .Values.networking.istio.enabled (eq .Values.installMode.type "multi-user") }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: seaweedfs-service
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.authorizationPolicyLabels" . | nindent 4 }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: seaweedfs
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ include "kubeflow-pipelines.namespace" . }}/sa/ml-pipeline
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ include "kubeflow-pipelines.namespace" . }}/sa/ml-pipeline-ui
  # Allow traffic to s3 endpoint from User Pipeline Pods, which don't have a sidecar.
  # Also needed for traffic from seaweedfs init pod. Seaweedfs gives the client an ip to connect to. This can not be
  # handled well by istio (AuthPolicy). Instead, access to the sensitive ports will be limited by the NetworkPolicy.
  - {}
{{- end }}

