{{- if .Values.seaweedfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-pvc
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ dig "persistence" "size" "20Gi" .Values.seaweedfs }}
{{- end }}

