{{- if .Values.seaweedfs.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: mlpipeline-minio-artifact
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
stringData:
  accesskey: {{ dig "credentials" "accesskey" "minio" .Values.seaweedfs }}
  secretkey: {{ dig "credentials" "secretkey" "minio123" .Values.seaweedfs }}
{{- end }}

