apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth.yaml
  - cert-manager.yaml
  - istio-system.yaml
  - knative-serving.yaml
  - kubeflow.yaml
  - kubeflow-system.yaml
  - oauth2-proxy.yaml
