apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- cluster-jwks-proxy.yaml

images:
- name: docker.io/bitnami/kubectl
  newName: docker.io/bitnamisecure/kubectl
  newTag: latest
