apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- model-registry-db-pvc.yaml
- model-registry-db-deployment.yaml
- model-registry-db-service.yaml
- ../../base


configMapGenerator:
- envs:
  - params.env
  name: model-registry-db-parameters
secretGenerator:
- envs:
  - secrets.env
  name: model-registry-db-secrets
generatorOptions:
  disableNameSuffixHash: true


images:
- name: postgres
  newName: postgres
  newTag: "16-alpine"

patches:
- path: patches/model-registry-deployment.yaml
replacements:
- source:
    fieldPath: data.POSTGRES_PORT
    kind: ConfigMap
    name: model-registry-db-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.template.metadata.annotations.[traffic.sidecar.istio.io/excludeOutboundPorts]
    select:
      group: apps
      kind: Deployment
      name: model-registry-deployment
      version: v1
