bases:
- ../../base

resources:
- certificate.yaml

patchesStrategicMerge:
- mutating-webhook-configuration.yaml
- deployment.yaml

configMapGenerator:
- name: admission-webhook-parameters
  behavior: merge
  env: params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
# These vars are used to substitute in the namespace, service name and
# deployment name into the mutating WebHookConfiguration.
# Since its a CR kustomize isn't aware of those fields and won't
# transform them.
# We need the var names to be relatively unique so that when we
# compose with other applications they won't conflict.
- name: podDefaultsIssuer
  objref:
    kind: ConfigMap
    name: admission-webhook-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.issuer
- name: podDefaultsCertName
  objref:
      kind: Certificate
      group: cert-manager.io
      version: v1alpha2
      name: admission-webhook-cert
  fieldref:
    fieldpath: metadata.name

configurations:
- params.yaml