apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- persistent-volume.yaml
patchesStrategicMerge:
- persistent-volume-claim.yaml
configMapGenerator:
- name: minio-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: minioPd
  objref:
    kind: ConfigMap
    name: minio-parameters
    apiVersion: v1
  fieldref:
      fieldpath: data.minioPd
- name: minioPvName
  objref:
    kind: ConfigMap
    name: minio-parameters
    apiVersion: v1
  fieldref:
      fieldpath: data.minioPvName
configurations:
- params.yaml
