apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crd.yaml
- clusterrole-binding.yaml
- clusterrole.yaml
- deployment.yaml
- sa.yaml
- service.yaml
images:
- name: gcr.io/ml-pipeline/viewer-crd-controller
  newTag: '0.1.14'
configMapGenerator:
- name: viewer-parameters
  env: params.env
vars:
- name: viewer-namespace
  objref:
    kind: Service
    name: ml-pipeline-tensorboard-ui
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: viewer-clusterDomain
  objref:
    kind: ConfigMap
    name: viewer-parameters
    version: v1
  fieldref:
    fieldpath: data.viewerClusterDomain
configurations:
- params.yaml
