apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../generic
- catalog-condition.yaml

patchesStrategicMerge:
- metadata-writer-role.yaml
- ml-pipeline-apiserver-role.yaml
- ml-pipeline-persistenceagent-role.yaml
- ml-pipeline-ui-role.yaml
- pipeline-runner-role.yaml
