# This overlay uses CertManager to provision a certificate for the
# PodDefaults admission controller. This is preferred over the old
# way of using "bootstrap" which was running a shell script to create
# the certificate.
# TODO(jlewi): We should eventually refactor the manifests to delete
# bootstrap and use certmanager by default.

resources:
- certificate.yaml
- ../../base

namespace: kubeflow

namePrefix: admission-webhook-



generatorOptions:
  disableNameSuffixHash: true

# These vars are used to substitute in the namespace, service name and
# deployment name into the mutating WebHookConfiguration.
# Since its a CR kustomize isn't aware of those fields and won't
# transform them.
# We need the var names to be relatively unique so that when we
# compose with other applications they won't conflict.
vars:
- fieldref:
    fieldPath: metadata.name
  name: podDefaultsCertName
  objref:
    group: cert-manager.io
    kind: Certificate
    name: cert
    version: v1

configurations:
- params.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
    app.kubernetes.io/name: poddefaults
    kustomize.component: poddefaults
patches:
- path: mutating-webhook-configuration.yaml
- path: deployment.yaml
