apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-python
  labels:
    sidecar.istio.io/inject: "false"
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark:3.5.2
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: 3.5.2
  driver:
    cores: 1
    memory: 512m
    serviceAccount: default-editor
    labels:
      sidecar.istio.io/inject: "false"
    securityContext:
      capabilities:
        drop:
          - ALL
      runAsUser: 185
      runAsGroup: 0
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
  executor:
    instances: 1
    cores: 1
    memory: 512m
    labels:
      sidecar.istio.io.inject: "false"
    securityContext:
      capabilities:
        drop:
          - ALL
      runAsUser: 185
      runAsGroup: 0
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
