apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
  labels:
    component: server
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: container
        image: gcr.io/tfx-oss-public/ml_metadata_store_server:0.14.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: metadata-db-secrets
                key: MYSQL_ROOT_PASSWORD
        command: ["/bin/metadata_store_server"]
        args: ["--grpc_port=8080",
               "--mysql_config_host=metadata-db.kubeflow",
               "--mysql_config_database=metadb",
               "--mysql_config_port=3306",
               "--mysql_config_user=root",
               "--mysql_config_password=$(MYSQL_ROOT_PASSWORD)"
        ]
        ports:
        - name: backendapi
          containerPort: 8080
