apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: kubeflow
commonLabels:
  kustomize.component: mpi-operator
  app: mpi-operator
  app.kubernetes.io/name: mpi-operator
  app.kubernetes.io/component: mpijob
images:
- name: mpioperator/mpi-operator
  newName: mpioperator/mpi-operator
  newTag: 0.3.0
