namespace: kubeflow
resources:
- persistent-volume-claim.yaml
- config-map.yaml
- secret.yaml
- cluster-role.yaml
- service-account.yaml
- cluster-role-binding.yaml
- service.yaml
- deployment.yaml
configMapGenerator:
- name: katib-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
images:
- name: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller
  newTag: 7ade03b
  newName: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller
- name: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-manager
  newTag: 7ade03b
  newName: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-manager
- name: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-manager-rest
  newTag: 7ade03b
  newName: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-manager-rest
- name: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui
  newTag: 7ade03b
  newName: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui
- name: mysql
  newTag: "8"
  newName: mysql
vars:
- name: clusterDomain
  objref:
    kind: ConfigMap
    name: katib-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.clusterDomain
- name: namespace
  objref:
    kind: Service
    name: katib-ui
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
configurations:
- params.yaml
