{{- if .Values.viewerCrd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-viewer-crd
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.viewerCrdLabels" . | nindent 4 }}
{{- if eq .Values.installMode.type "multi-user" }}
    application-crd-id: kubeflow-pipelines
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kubeflow-pipelines.viewerCrdSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        {{- include "kubeflow-pipelines.viewerCrdLabels" . | nindent 8 }}
{{- if eq .Values.installMode.type "multi-user" }}
        application-crd-id: kubeflow-pipelines
{{- end }}
    spec:
      serviceAccountName: ml-pipeline-viewer-crd-service-account
      containers:
      - name: ml-pipeline-viewer-crd
        image: {{ include "kubeflow-pipelines.image" (dict "repository" .Values.viewerCrd.image.repository "tag" .Values.viewerCrd.image.tag "context" .) }}
        imagePullPolicy: {{ .Values.viewerCrd.image.pullPolicy | default .Values.global.imagePullPolicy }}
        env:
        {{- range .Values.viewerCrd.additionalEnv }}
        - name: {{ .name }}
          {{- if hasKey . "value" }}
          value: {{ .value | quote }}
          {{- else if and (hasKey . "valueFrom") .valueFrom (not (eq .valueFrom nil)) }}
          valueFrom:
            {{- toYaml .valueFrom | nindent 12 }}
          {{- else if eq .name "NAMESPACE" }}
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
          {{- else }}
          value: ""
          {{- end }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.viewerCrd.securityContext | nindent 10 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
{{- end }}
