{{- if .Values.ui.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "kubeflow-pipelines.uiLabels" . | nindent 4 }}
  name: ml-pipeline-ui
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ml-pipeline-ui
subjects:
- kind: ServiceAccount
  name: ml-pipeline-ui
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
{{- end }}
