apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- namespace.yaml
- ../third-party/application/cluster-scoped
- ../third-party/argo/installs/namespace/cluster-scoped
- ../base/pipeline/cluster-scoped
- ../base/cache-deployer/cluster-scoped
# NOTE: var name must be unique globally to allow composition of multiple kustomize
# packages. Therefore, we added prefix `kfp-cluster-scoped-` to distinguish it from
# others.
    # cache deployer sa's metadata.namespace will be first transformed by namespace field in kustomization.yaml
    # so that we only need to change kustomization.yaml's namespace field for namespace customization.
vars:
- fieldref:
    fieldPath: metadata.namespace
  name: kfp-cluster-scoped-namespace
  objref:
    apiVersion: v1
    kind: ServiceAccount
    name: kubeflow-pipelines-cache-deployer-sa
configurations:
- params.yaml
