# Adds namespace to all resources.
# Note: the namespace name needs to be changed here and cannot be changed in an overlay
# This is because certmanager and webhook use kustomize names to configure resources.
# Setting another namespace here as in the overlay will lead to e.g. wrong DNSNames being generated.
namespace: kubeflow

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: pvcviewer-

# Labels to add to all resources and selectors.

resources:
- ../crd
- ../rbac
- ../manager
- ../webhook
- ../certmanager
# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
#- ../prometheus

# Do not create a namespace
# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: CERTIFICATE_NAMESPACE
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref: {}
  name: CERTIFICATE_NAME
  objref:
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
- fieldref:
    fieldPath: metadata.namespace
  name: SERVICE_NAMESPACE
  objref:
    kind: Service
    name: webhook-service
    version: v1
- fieldref: {}
  name: SERVICE_NAME
  objref:
    kind: Service
    name: webhook-service
    version: v1

# the following config is for teaching kustomize how to replace vars in Certificates.
configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: pvcviewer
patches:
- path: remove_namespace.yaml
- path: manager_auth_proxy_patch.yaml
- path: manager_webhook_patch.yaml
- path: cainjection_patch.yaml
- path: dnsnames_patch.yaml
