{{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kserve-models-web-app.fullname" . }}
  namespace: {{ include "kserve-models-web-app.namespace" . }}
  labels:
    {{- include "kserve-models-web-app.labels" . | nindent 4 }}
    {{- include "kserve-models-web-app.kustomizeLabels" . | nindent 4 }}
    {{- if .Values.kubeflow.enabled }}
    {{- include "kserve-models-web-app.kserveLabels" . | nindent 4 }}
    {{- end }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "kserve-models-web-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kserve-models-web-app.selectorLabels" . | nindent 8 }}
        {{- include "kserve-models-web-app.kustomizeLabels" . | nindent 8 }}
        {{- if .Values.kubeflow.enabled }}
        {{- include "kserve-models-web-app.kserveLabels" . | nindent 8 }}
        {{- end }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.app.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.kubeflow.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.app.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kserve-models-web-app.serviceAccountName" . }}
      {{- with .Values.app.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "kserve-models-web-app.image" . }}
        imagePullPolicy: {{ include "kserve-models-web-app.imagePullPolicy" . }}
        {{- with .Values.app.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.app.containerPort }}
        {{- if .Values.configMap.create }}
        envFrom:
        - configMapRef:
            name: {{ include "kserve-models-web-app.configMapName" . }}
        {{- end }}
        {{- if .Values.app.config.env }}
        env:
        {{- range .Values.app.config.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.app.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.app.livenessProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
          successThreshold: {{ .Values.app.livenessProbe.successThreshold }}
        {{- end }}
        {{- if .Values.app.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.app.readinessProbe.path }}
            port: http
          initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
          successThreshold: {{ .Values.app.readinessProbe.successThreshold }}
        {{- end }}
        {{- with .Values.app.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.app.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.app.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 