apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pipeline-resource.yaml
patchesJson6902:
- target:
    group: tekton.dev
    version: v1alpha1
    kind: PipelineRun
    name: $(generateName)
  path: pipeline-run-patch.yaml
configMapGenerator:
- name: kfctl-repo-resource-parameters
  env: params.env
vars:
- name: kfctl_repo_revision
  objref:
    kind: ConfigMap
    name: kfctl-repo-resource-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.kfctl_repo_revision
- name: kfctl_repo_url
  objref:
    kind: ConfigMap
    name: kfctl-repo-resource-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.kfctl_repo_url
configurations:
- params.yaml
