apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
- service.yaml
namePrefix: jupyter-web-app-
namespace: kubeflow
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
images:
- name: gcr.io/kubeflow-images-public/jupyter-web-app
  newName: gcr.io/kubeflow-images-public/jupyter-web-app
  newTag: vmaster-gd9be4b9e
configMapGenerator:
- envs:
  - params.env
  name: parameters
# We need the name to be unique without the suffix because the original name is what
# gets used with patches
- name: jupyter-web-app-config
  files:
  - configs/spawner_ui_config.yaml
generatorOptions:
  # TODO(jlewi): Why are we setting disableNameSuffixHash true? Don't we want a content hash so that if the config map
  # changes we would update the configmap?
  disableNameSuffixHash: true
vars:
- fieldref:
    fieldPath: data.policy
  name: policy
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.prefix
  name: prefix
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
# TODO(jlewi): This is commented out because when we combine applicaitons
# we can't have multiple vars with the same name
#- fieldref:
#    fieldPath: metadata.namespace
#  name: namespace
#  objref:
#    apiVersion: v1
#    kind: Service
#    name: service
- fieldref:
    fieldPath: data.userid-header
  name: userid-header
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.userid-prefix
  name: userid-prefix
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
configurations:
- params.yaml
