apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- clusterstoragecontainer.yaml
images:
- name: ghcr.io/kubeflow/model-registry/storage-initializer
  newName: ghcr.io/kubeflow/model-registry/storage-initializer
  newTag: v0.3.4
