apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- pipelines-runner/base
- api-service/base
- scheduledworkflow/base
- minio/base
- mysql/base
- pipelines-ui/base
- pipelines-viewer/base
- persistent-agent/base
commonLabels:
  kustomize.component: pipeline
