{{- if and (eq .Values.installMode.type "multi-user") (eq .Values.installMode.pipelineDefinition.storage "k8s-native") }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pipelineversions.pipelines.kubeflow.org
  annotations:
    cert-manager.io/inject-ca-from: {{ include "kubeflow-pipelines.namespace" . }}/kfp-api-webhook-cert
webhooks:
  - name: pipelineversions.pipelines.kubeflow.org
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - pipelines.kubeflow.org
        apiVersions:
          - v2beta1
        resources:
          - pipelineversions
        scope: Namespaced
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: {{ .Values.webhooks.failurePolicy | default "Fail" }}
    clientConfig:
      service:
        name: ml-pipeline
        namespace: {{ include "kubeflow-pipelines.namespace" . }}
        path: /webhooks/validate-pipelineversion
        port: 8443
{{- end }}

