apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- application.yaml
configMapGenerator:
- name: seldon-core-operator-parameters
  env: params.env
vars:
- name: generateName
  objref:
    kind: ConfigMap
    name: seldon-core-operator-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.generateName
configurations:
- params.yaml
commonLabels:
  app.kubernetes.io/name: seldon-core-operator  
  app.kubernetes.io/instance: $(generateName)
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: seldon
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
