{{- if and (not .Values.externalDatabase.existingSecret) (not .Values.mysql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.externalDatabase.username | quote }}
  password: {{ .Values.externalDatabase.password | quote }}
{{- end }}
