apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: notebook-controller-
namespace: kubeflow
commonLabels:
  app: notebook-controller
  app.kubernetes.io/component: notebook-controller
  app.kubernetes.io/name: notebook-controller
  kustomize.component: notebook-controller
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
  name: config
images:
- name: gcr.io/kubeflow-images-public/notebook-controller
  newName: gcr.io/kubeflow-images-public/notebook-controller
  newTag: vmaster-g6eb007d0
patchesStrategicMerge:
- deployment_patch.yaml
resources:
- ../../../../../jupyter/notebook-controller/base/cluster-role-binding.yaml
- ../../../../../jupyter/notebook-controller/base/cluster-role.yaml
- ../../../../../jupyter/notebook-controller/base/crd.yaml
- ../../../../../jupyter/notebook-controller/base/deployment.yaml
- ../../../../../jupyter/notebook-controller/base/service-account.yaml
- ../../../../../jupyter/notebook-controller/base/service.yaml
