bases:
- ../base
images:
- name: gcr.io/kubeflow-images-public/profile-controller
  newTag: v20190228-v0.4.0-rc.1-192-g1a802656-dirty-f95773
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
