
{{- if .Values.additionalServiceAccounts.containerBuilder.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-pipelines-container-builder
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
  {{- with .Values.additionalServiceAccounts.containerBuilder.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.additionalServiceAccounts.pipelineRunner.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-runner
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
  {{- with .Values.additionalServiceAccounts.pipelineRunner.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.additionalServiceAccounts.viewer.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-pipelines-viewer
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
  {{- with .Values.additionalServiceAccounts.viewer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
