{{- if eq .Values.installMode.type "multi-user" }}
# API Server ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ml-pipeline
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ml-pipeline
subjects:
- kind: ServiceAccount
  name: ml-pipeline
  namespace: {{ include "kubeflow-pipelines.namespace" . }}

---
# UI ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ml-pipeline-ui
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app: ml-pipeline-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ml-pipeline-ui
subjects:
- kind: ServiceAccount
  name: ml-pipeline-ui
  namespace: {{ include "kubeflow-pipelines.namespace" . }}

---
# Scheduled Workflow ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ml-pipeline-scheduledworkflow-binding
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ml-pipeline-scheduledworkflow-role
subjects:
- kind: ServiceAccount
  name: ml-pipeline-scheduledworkflow
  namespace: {{ include "kubeflow-pipelines.namespace" . }}

---
# Persistence Agent ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ml-pipeline-persistenceagent-binding
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ml-pipeline-persistenceagent-role
subjects:
- kind: ServiceAccount
  name: ml-pipeline-persistenceagent
  namespace: {{ include "kubeflow-pipelines.namespace" . }}

---
# Viewer Controller ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ml-pipeline-viewer-crd-binding
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ml-pipeline-viewer-controller-role
subjects:
- kind: ServiceAccount
  name: ml-pipeline-viewer-crd-service-account
  namespace: {{ include "kubeflow-pipelines.namespace" . }}

---
# Cache ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-pipelines-cache-binding
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app: cache-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-pipelines-cache-role
subjects:
- kind: ServiceAccount
  name: kubeflow-pipelines-cache
  namespace: {{ include "kubeflow-pipelines.namespace" . }}

---
# Metadata Writer ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeflow-pipelines-metadata-writer-binding
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-pipelines-metadata-writer-role
subjects:
- kind: ServiceAccount
  name: kubeflow-pipelines-metadata-writer
  namespace: {{ include "kubeflow-pipelines.namespace" . }}

{{- if .Values.thirdParty.argo.enabled }}
---
# Argo ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-binding
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-cluster-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
{{- end }}

---
# Metacontroller ClusterRoleBinding
{{- if .Values.thirdParty.metacontroller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meta-controller-cluster-role-binding
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-metacontroller
subjects:
- kind: ServiceAccount
  name: meta-controller-service
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
{{- end }}
{{- end }}
