apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- persistent-volume.yaml
patchesStrategicMerge:
- persistent-volume-claim.yaml
configMapGenerator:
- name: overlay-params
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: mysqlPd
  objref:
    kind: ConfigMap
    name: overlay-params
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlPd
- name: mysqlPvName
  objref:
    kind: ConfigMap
    name: overlay-params
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlPvName
configurations:
- params.yaml
