apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: jupyter-web-app-application
spec:
  type: jupyter-web-app
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: core
    kind: ServiceAccount
  - group: networking.istio.io
    kind: VirtualService
  version: v1alpha1
  description: Replaces JupyterHub Spawner UI with a new Jupyter UI whcih enables to create/conect/delete jupyter notebooks.
  icons:
  maintainers:
    - name: Kimonas Sotirchos
      email: kimwnasptd@arrikto.com
  owners:
    - name: Kimonas Sotirchos
      email: kimwnasptd@arrikto.com
  keywords:
   - jupyterhub
   - jupyter ui
   - notebooks  
  links:
    - description: About
      url: https://github.com/kubeflow/kubeflow/tree/master/components/jupyter-web-app
    - description: Docs
      url: https://www.kubeflow.org/docs/notebooks 
