apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- application.yaml
configMapGenerator:
- name: jupyter-web-app-parameters
  env: params.env
vars:
- name: generateName
  objref:
    kind: ConfigMap
    name: jupyter-web-app-parameters 
    apiVersion: v1
  fieldref:
    fieldpath: data.generateName
configurations:
- params.yaml
commonLabels:
  app.kubernetes.io/name: jupyter-web-app
  app.kubernetes.io/instance: $(generateName)
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: jupyter
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
