---
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"envoy":"iap-backendconfig"}}'
  labels:
    service: envoy
  name: envoy-service
spec:
  ports:
  - name: envoy
    port: 8080
    targetPort: 8080
  selector:
    service: envoy
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami
  name: whoami-app
spec:
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: whoami
  type: ClusterIP
