# Kubeflow-specific dex customizations
# Includes: NetworkPolicy for auth namespace
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../oauth2-proxy
- default-allow-same-namespace.yaml
