apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- cluster-local-gateway-requestauthentication.yaml
- cluster-local-gateway-authorizationpolicy-deny.yaml

patches:
- path: cluster-local-gateway-authorizationpolicy-patch.yaml
