apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: jupyter-web-app
  app.kubernetes.io/name: jupyter-web-app
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
namePrefix: jupyter-web-app-
namespace: kubeflow
images:
- name: gcr.io/kubeflow-images-public/jupyter-web-app
  newName: gcr.io/kubeflow-images-public/jupyter-web-app
  newTag: vmaster-ge4456300
resources:
- ../../../../../jupyter/jupyter-web-app/base/cluster-role-binding.yaml
- ../../../../../jupyter/jupyter-web-app/base/cluster-role.yaml
- ../../../../../jupyter/jupyter-web-app/base/deployment.yaml
- ../../../../../jupyter/jupyter-web-app/base/role-binding.yaml
- ../../../../../jupyter/jupyter-web-app/base/role.yaml
- ../../../../../jupyter/jupyter-web-app/base/service-account.yaml
- ../../../../../jupyter/jupyter-web-app/base/service.yaml
patchesStrategicMerge:
- deployment_patch.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: jupyter-web-app-config
  files:
  - ../../../../../jupyter/jupyter-web-app/base/configs/spawner_ui_config.yaml
- name: parameters
  envs:
  - params.env
vars:
- fieldref:
    fieldPath: data.policy
  name: policy
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.prefix
  name: prefix
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
configurations:
- params.yaml
