apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: webapp_mapping
      prefix: /jupyter/
      service: jupyter-web-app.kubeflow
      add_request_headers:
       x-forwarded-prefix: /jupyter
  labels:
    run: jupyter-web-app
  name: jupyter-web-app
  namespace: kubeflow
  spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: jupyter-web-app
  type: ClusterIP