apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/runtimes

# Update the Kubeflow LLM Trainer image tag.
images:
  - name: ghcr.io/kubeflow/trainer/torchtune-trainer
    newTag: v2.1.0
  - name: ghcr.io/kubeflow/trainer/dataset-initializer
    newTag: v2.1.0
  - name: ghcr.io/kubeflow/trainer/model-initializer
    newTag: v2.1.0
  - name: ghcr.io/kubeflow/trainer/mlx-runtime
    newTag: v2.1.0
  - name: ghcr.io/kubeflow/trainer/deepspeed-runtime
    newTag: v2.1.0
