apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- model-registry-ui-role.yaml
- model-registry-ui-service.yaml
- model-registry-ui-deployment.yaml
- model-registry-ui-service-account.yaml

images:
- name: model-registry-ui
  newName: ghcr.io/kubeflow/model-registry/ui
  newTag: v0.3.4
