apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- application.yaml
configMapGenerator:
- name: kfserving-parameters
  behavior: merge
  env: params.env
vars:
- name: generateName
  objref:
    kind: ConfigMap
    name: kfserving-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.generateName
configurations:
- params.yaml
commonLabels:
  app.kubernetes.io/name: kfserving  
  app.kubernetes.io/instance: $(generateName)
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: serving
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
