apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
configMapGenerator:
- literals:
  - RWO_PVC_SCHEDULING="True"
  - TENSORBOARD_IMAGE=tensorflow/tensorflow:2.5.1
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
  - ISTIO_HOST=*
  name: tensorboard-controller-config
images:
- name: ghcr.io/kubeflow/kubeflow/tensorboard-controller
  newName: ghcr.io/kubeflow/kubeflow/tensorboard-controller
  newTag: v1.10.0
patches:
- path: patches/add_controller_config.yaml
