apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cache-server.yaml
- centraldashboard.yaml
- default-allow-same-namespace.yaml
- default-allow-same-namespace-kubeflow-system.yaml
- jupyter-web-app.yaml
- katib-controller.yaml
- katib-db-manager.yaml
- katib-ui.yaml
- kserve-models-web-app.yaml
- kserve.yaml
- metadata-envoy.yaml
- metadata-grpc-server.yaml
- minio.yaml
- ml-pipeline-ui.yaml
- ml-pipeline.yaml
- model-catalog.yaml
- model-registry.yaml
- model-registry-ui.yaml
- poddefaults.yaml
- pvcviewer-webhook.yaml
- spark-operator-webhook.yaml
- tensorboards-web-app.yaml
- trainer-webhook-kubeflow-system.yaml
- jobset-webhook-kubeflow-system.yaml
- training-operator-webhook.yaml
- volumes-web-app.yaml
