# DO Not submit
# hack to test configmap substitution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testconfigmap
spec:
  template:
    spec:
        containers:
          - name: centraldashboard
            env:
            - name: USERID_HEADER
              valueFrom:
                configMapKeyRef:
                  name: kubeflow-config
                  key: userid-header
            - name: USERID_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: kubeflow-config
                  key: userid-prefix
            - name: PROFILES_KFAM_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: kubeflow-config
                  key: profiles_kfam_service_host
