name: Build & Apply Katib manifests in KinD
on:
  pull_request:
    paths:
      - .github/workflows/katib_test.yaml
      - apps/katib/upstream/**
      - tests/gh-actions/kind-cluster.yaml
      - tests/gh-actions/install_kind.sh
      - tests/gh-actions/install_kustomize.sh
      - tests/gh-actions/install_istio.sh
      - tests/gh-actions/install_cert_manager.sh
      - common/cert-manager/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install KinD
      run: ./tests/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config tests/gh-actions/kind-cluster.yaml

    - name: Install kustomize
      run: ./tests/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./tests/gh-actions/install_istio.sh

    - name: Install cert-manager
      run: ./tests/gh-actions/install_cert_manager.sh

    # https://kind.sigs.k8s.io/docs/user/known-issues/#apparmor
    - name: AppArmor
      run: |
        set -x
        sudo apt-get install apparmor-profiles
        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

    - name: Build & Apply manifests
      run: |
        cd apps/katib/upstream
        kubectl create ns kubeflow
        kustomize build installs/katib-with-kubeflow | kubectl apply -f -
        kubectl wait --for=condition=Ready pods --all -n kubeflow --timeout 300s

    - name: Create katib experiment
      run: |
        kubectl create namespace kubeflow-user
        kubectl label namespace kubeflow-user katib.kubeflow.org/metrics-collector-injection=enabled
        kubectl apply -f tests/gh-actions/kf-objects/katib_test.yaml

        echo "Waiting for Experiment to become Running..."
        kubectl wait --for=condition=Running experiments.kubeflow.org -n kubeflow-user --all --timeout 300s

        echo "Waiting for all Trials to become Succeeded..."
        kubectl wait --for=condition=Succeeded trials.kubeflow.org -n kubeflow-user --all --timeout 300s

        echo "Waiting for the Experiment to become Succeeded..."
        kubectl wait --for=condition=Succeeded experiments.kubeflow.org -n kubeflow-user --all --timeout 300s
