name: Build & Apply Kubeflow Pipelines manifests in KinD
on:
  pull_request:
    paths:
      - apps/pipeline/upstream/**
      - tests/gh-actions/kind-cluster.yaml
      - tests/gh-actions/install_istio.sh
      - common/cert-manager/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install KinD
      run: ./tests/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config tests/gh-actions/kind-cluster.yaml

    - name: Install kustomize
      run: ./tests/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./tests/gh-actions/install_istio.sh

    - name: Install cert-manager
      run: ./tests/gh-actions/install_cert_manager.sh

    - name: Build & Apply manifests
      run: ./tests/gh-actions/install_pipelines.sh

    - name: Deploy test pipeline
      run: |
        pip3 install kfp==1.8.4
        kustomize build apps/profiles/upstream/overlays/kubeflow | kubectl apply -f -
        kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout 180s
        kustomize build common/user-namespace/base | kubectl apply -f -
        kustomize build common/kubeflow-roles/base | kubectl apply -f -
        ./tests/e2e/hack/proxy_pipelines.sh
        kubectl apply -f tests/e2e/yamls
        python3 ./tests/gh-actions/kf-objects/test_pipeline.py
        ./tests/gh-actions/install_argo_cli.sh
        argo wait @latest -n kubeflow-user-example-com --request-timeout 60
