name: Build & Apply Profiles manifests in KinD
on:
  pull_request:
    paths:
      - apps/profiles/upstream/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install KinD
      run: ./tests/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config tests/gh-actions/kind-cluster-1-22.yaml

    - name: Install kustomize
      run: ./tests/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./tests/gh-actions/install_istio.sh

    - name: Build & Apply manifests
      run: |
        cd apps/profiles/upstream
        kubectl create ns kubeflow
        kustomize build overlays/kubeflow | kubectl apply -f -
        kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout 180s
