apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../istio
- default-allow-same-namespace.yaml
- allow-istio-and-oauth2-proxy.yaml

patches:
- path: config-map.yaml
  target:
    version: v1
    kind: ConfigMap
    name: dex
    namespace: auth
